### ISSUE TITLE
Service NotFound

### ISSUE THREAD

**Issue by apoca** [facile-it/sentry-module#10]
I have followed the installation and I am getting this:

Fatal error: Uncaught Zend\ServiceManager\Exception\ServiceNotFoundException: Zend\ServiceManager\ServiceManager::get was unable to fetch or create an instance for Facile\SentryModule\Listener\ErrorHandlerListener in /var/www/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:555 Stack trace: #0 /var/www/module/Application/src/Module.php(39): Zend\ServiceManager\ServiceManager->get('Facile\\SentryMo...') #1 [internal function]: Application\Module->onBootstrap(Object(Zend\Mvc\MvcEvent)) #2 /var/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent)) #3 /var/www/vendor/zendframework/zend-eventmanager/src/EventManager.php(248): Zend\EventManager\EventManager->triggerListeners('bootstrap', Object(Zend\Mvc\MvcEvent)) #4 /var/www/vendor/zendframework/zend-mvc/src/Application.php(169): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent)) #5 /var/www/vendor/zendframework/zend-mvc/src/Application.php(281): Zend\Mvc\Application->bootstrap in /var/www/vendor/zendframework/zend-servicemanager/src/ServiceManager.php on line 555

**Comment by thomasvargiu** [comment]
Sorry for the late reply. I think you are trying to fetch the listener before the sentry module is loaded.
