### ISSUE TITLE
Upgrade Sentry SDK to version 3

### ISSUE THREAD

**Issue by metalinspired** [facile-it/sentry-module#17]

**Comment by steefmin** [comment]
Is there any idea when 3.0.0 might be released? Seems to be in Beta since 2020-11.

**Comment by gloomy** [comment]
Waiting for a release as well 👍

**Comment by thomasvargiu** [comment]
There was a `3.0.0-beta1` from November 2020.

[`3.0.0`](https://github.com/facile-it/sentry-module/releases/tag/3.0.0) is released now
