### ISSUE TITLE
Does not bootstrap in Laminas CLI

### ISSUE THREAD

**Issue by datasage** [facile-it/sentry-module#19]
Currently this module relies on `onBootstrap` to bootstrap sentry into the environment. This is only called when used with an mvc controller. Laminas CLI does not call onBootstrap when initializing a module. 

It does however call init, and there is a post init event which may be an opportunity to bootstrap the module in a different way. I am exploring some options to allow it to work with laminas cli and the mvc stack.

**Comment by thomasvargiu** [comment]
You can just get the `HubInterface` whenever you want to initialize it:

```php
use Sentry\HubInterface;

$container->get(HubInterface::class);
```
